# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controller.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(393, 507)
        self.btn_forward = QtWidgets.QPushButton(Form)
        self.btn_forward.setGeometry(QtCore.QRect(151, 110, 89, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_forward.setFont(font)
        self.btn_forward.setObjectName("btn_forward")
        self.btn_reverse = QtWidgets.QPushButton(Form)
        self.btn_reverse.setGeometry(QtCore.QRect(151, 230, 89, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_reverse.setFont(font)
        self.btn_reverse.setObjectName("btn_reverse")
        self.btn_turnRight = QtWidgets.QPushButton(Form)
        self.btn_turnRight.setGeometry(QtCore.QRect(261, 171, 89, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_turnRight.setFont(font)
        self.btn_turnRight.setObjectName("btn_turnRight")
        self.btn_turnLeft = QtWidgets.QPushButton(Form)
        self.btn_turnLeft.setGeometry(QtCore.QRect(41, 171, 89, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_turnLeft.setFont(font)
        self.btn_turnLeft.setObjectName("btn_turnLeft")
        self.btn_rotateLeft = QtWidgets.QPushButton(Form)
        self.btn_rotateLeft.setGeometry(QtCore.QRect(40, 20, 60, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_rotateLeft.setFont(font)
        self.btn_rotateLeft.setObjectName("btn_rotateLeft")
        self.btn_rotateRight = QtWidgets.QPushButton(Form)
        self.btn_rotateRight.setGeometry(QtCore.QRect(291, 20, 60, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_rotateRight.setFont(font)
        self.btn_rotateRight.setObjectName("btn_rotateRight")
        self.btn_stop = QtWidgets.QPushButton(Form)
        self.btn_stop.setGeometry(QtCore.QRect(161, 20, 70, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btn_stop.setFont(font)
        self.btn_stop.setObjectName("btn_stop")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 80, 71, 17))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(280, 80, 91, 17))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(175, 80, 41, 17))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(160, 160, 61, 17))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(165, 280, 61, 17))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(260, 220, 91, 17))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(40, 220, 91, 17))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pub_command = QtWidgets.QLabel(Form)
        self.pub_command.setGeometry(QtCore.QRect(60, 350, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pub_command.setFont(font)
        self.pub_command.setAlignment(QtCore.Qt.AlignCenter)
        self.pub_command.setObjectName("pub_command")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(90, 320, 211, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_forward.setText(_translate("Form", "↑"))
        self.btn_reverse.setText(_translate("Form", "↓"))
        self.btn_turnRight.setText(_translate("Form", "→"))
        self.btn_turnLeft.setText(_translate("Form", "←"))
        self.btn_rotateLeft.setText(_translate("Form", "↺"))
        self.btn_rotateRight.setText(_translate("Form", "↻"))
        self.btn_stop.setText(_translate("Form", "⊝"))
        self.label.setText(_translate("Form", "Rotasi Kiri"))
        self.label_2.setText(_translate("Form", "Rotasi Kanan"))
        self.label_3.setText(_translate("Form", "Stop"))
        self.label_4.setText(_translate("Form", "Forward"))
        self.label_5.setText(_translate("Form", "Reverse"))
        self.label_6.setText(_translate("Form", "Belok Kanan"))
        self.label_7.setText(_translate("Form", "Belok Kiri"))
        self.pub_command.setText(_translate("Form", "Puts teks here.."))
        self.label_8.setText(_translate("Form", "Publisher Command:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
