<?xml version="1.0" ?>

<robot name="trainer_bot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find trainer_robot_description)/urdf/common_properties.xacro"/>

  <xacro:property name="base_width" value="0.08" /> <!-- Base -->
  <xacro:property name="base_length" value="0.15" /> <!-- Base -->
  <xacro:property name="base_height" value="0.015" /> <!-- Base -->
  <xacro:property name="wheel_length" value="0.02" /> <!-- Wheel -->
  <xacro:property name="wheel_radius" value="0.04" /> <!-- Wheel -->
  <xacro:property name="distance_from_middle_wheels" value="0.06" /> <!-- Wheel -->

  <xacro:macro name="wheel_continuous" params="name type distance_from_middle_wheels distance_from_base radius length mu1 mu2 mass">
    <joint name="${name}_joint" type="${type}">
      <parent link="base_link"/>
      <child link="${name}_link"/>
      <origin xyz="${distance_from_middle_wheels} ${distance_from_base} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${length * 0.8}"/>
        </geometry>
        <material name="black"/>
      </collision>
      <inertial>
        <mass value="${mass}"/>
        <inertia 
                  ixx="${0.083*mass*(3*radius*radius+length*length)}" 
                  ixy="0.0" 
                  ixz="0.0" 
                  iyy="${0.083*mass*(3*radius*radius+length*length)}" 
                  iyz="0.0" 
                  izz="${0.5*mass*(radius*radius)}" />
      </inertial>
    </link>
	  <transmission name="${name}_trans">
	  	<type>transmission_interface/SimpleTransmission</type>
	  	<joint name="${name}_joint">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
	  	</joint>
	  	<actuator name="${name}_motor">
	  		<mechanicalReduction>1</mechanicalReduction>
	  		<hardwareInterface>VelocityJointInterface</hardwareInterface>
	  	</actuator>
	  </transmission>
    <gazebo reference="${name}_link">
      <material>Gazebo/Black</material>
      <mu1>${mu1}</mu1>
      <mu2>${mu2}</mu2>
      <!-- <kp>500000.0</kp>
      <kd>10.0</kd> -->
      <!-- <minDepth>0.001</minDepth> -->
      <maxVel>1.0</maxVel>
      <fdir1>1 0 0</fdir1>
      <material>Gazebo/FlatBlack</material>
    </gazebo>
  </xacro:macro>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0" rpy="0 0 0"/>
  </joint>
  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0.0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0.0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="grey"/>
    </collision>
    <inertial>
      <mass value="${1}"/>
      <inertia 
                ixx="${0.083*1*(base_width+base_height)}" 
                ixy="0.0" 
                ixz="0.0" 
                iyy="${0.083*1*(base_length+base_height)}" 
                iyz="0.0" 
                izz="${0.083*1*(base_width+base_length)}" />
    </inertial>
  </link>

  <joint name="batter_holder_joint" type="fixed">
    <parent link="base_link"/>
    <child link="battery_holder_link"/>
    <origin xyz="${distance_from_middle_wheels} 0 0.015" rpy="0 0 0"/>
  </joint>

  <link name="battery_holder_link">
    <visual>
      <origin xyz="-0.095 0 0.015" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.06 0.025"/>
      </geometry>
      <material name="yellow"/>
    </visual>
    <collision>
      <origin xyz="-0.095 0 0.015" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.06 0.025"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <gazebo reference="battery_holder_link">
    <material>Gazebo/Yellow</material>
  </gazebo>

  <xacro:wheel_continuous name="left_front_wheel" type="continuous" distance_from_middle_wheels="${distance_from_middle_wheels}" distance_from_base="${wheel_length/2 + base_width/2}" radius="${wheel_radius}" length="${wheel_length}" mu1="1" mu2="1" mass="0.3" />
  <xacro:wheel_continuous name="right_front_wheel" type="continuous" distance_from_middle_wheels="${distance_from_middle_wheels}" distance_from_base="-${wheel_length/2 + base_width/2}" radius="${wheel_radius}" length="${wheel_length}" mu1="1" mu2="1" mass="0.3" />

  <xacro:wheel_continuous name="left_rear_wheel" type="continuous" distance_from_middle_wheels="-${distance_from_middle_wheels}" distance_from_base="${wheel_length/2 + base_width/2}" radius="${wheel_radius}" length="${wheel_length}" mu1="0.01" mu2="0.01" mass="0.3" />
  <xacro:wheel_continuous name="right_rear_wheel" type="continuous" distance_from_middle_wheels="-${distance_from_middle_wheels}" distance_from_base="-${wheel_length/2 + base_width/2}" radius="${wheel_radius}" length="${wheel_length}" mu1="0.01" mu2="0.01" mass="0.3" />
  
  <!-- <gazebo>
    <plugin name="robot_trainer_controller" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin>
  </gazebo> -->
  
	<gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <legacyMode>false</legacyMode>
      <alwaysOn>true</alwaysOn>
      <publishWheelTF>true</publishWheelTF>
      <publishTf>1</publishTf>
      <publishWheelJointState>true</publishWheelJointState>
      <updateRate>20.0</updateRate>
      <leftFrontJoint>left_front_wheel_joint</leftFrontJoint>
      <rightFrontJoint>right_front_wheel_joint</rightFrontJoint>
      <leftRearJoint>left_rear_wheel_joint</leftRearJoint>
      <rightRearJoint>right_rear_wheel_joint</rightRearJoint>
      <wheelSeparation>0.08</wheelSeparation>
      <wheelDiameter>0.08</wheelDiameter>
      <wheelAcceleration>1.0</wheelAcceleration>
      <torque>20</torque>
      <commandTopic>/cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <robotNamespace>/</robotNamespace>
      <odometrySource>world</odometrySource>
      <broadcastTF>true</broadcastTF>
    </plugin>
  </gazebo>
</robot>
